/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as ApiV1ConfigRouteImport } from './routes/api/v1/config'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1RenderRouteImport } from './routes/api/v1/render'
import { Route as ApiV1AdminMeRouteImport } from './routes/api/v1/admin/me'
import { Route as ApiV1CommentsIndexRouteImport } from './routes/api/v1/comments/index'
import { Route as ApiV1CommentsCountRouteImport } from './routes/api/v1/comments/count'
import { Route as ApiV1CommentsRecentRouteImport } from './routes/api/v1/comments/recent'
import { Route as ApiV1ThreadsSplatRouteImport } from './routes/api/v1/threads/$'
import { Route as ApiV1AdminCommentsIndexRouteImport } from './routes/api/v1/admin/comments/index'
import { Route as ApiV1AdminCommentsIdRouteImport } from './routes/api/v1/admin/comments/$id'
import { Route as ApiV1AdminCommentsBatchRouteImport } from './routes/api/v1/admin/comments/batch'
import { Route as ApiV1CommentsIdRepliesRouteImport } from './routes/api/v1/comments/$id/replies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConfigRoute = ApiV1ConfigRouteImport.update({
  id: '/api/v1/config',
  path: '/api/v1/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RenderRoute = ApiV1RenderRouteImport.update({
  id: '/api/v1/render',
  path: '/api/v1/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminMeRoute = ApiV1AdminMeRouteImport.update({
  id: '/api/v1/admin/me',
  path: '/api/v1/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommentsIndexRoute = ApiV1CommentsIndexRouteImport.update({
  id: '/api/v1/comments/',
  path: '/api/v1/comments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommentsCountRoute = ApiV1CommentsCountRouteImport.update({
  id: '/api/v1/comments/count',
  path: '/api/v1/comments/count',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommentsRecentRoute = ApiV1CommentsRecentRouteImport.update({
  id: '/api/v1/comments/recent',
  path: '/api/v1/comments/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ThreadsSplatRoute = ApiV1ThreadsSplatRouteImport.update({
  id: '/api/v1/threads/$',
  path: '/api/v1/threads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminCommentsIndexRoute = ApiV1AdminCommentsIndexRouteImport.update({
  id: '/api/v1/admin/comments/',
  path: '/api/v1/admin/comments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminCommentsIdRoute = ApiV1AdminCommentsIdRouteImport.update({
  id: '/api/v1/admin/comments/$id',
  path: '/api/v1/admin/comments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminCommentsBatchRoute = ApiV1AdminCommentsBatchRouteImport.update({
  id: '/api/v1/admin/comments/batch',
  path: '/api/v1/admin/comments/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommentsIdRepliesRoute = ApiV1CommentsIdRepliesRouteImport.update({
  id: '/api/v1/comments/$id/replies',
  path: '/api/v1/comments/$id/replies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/v1/config': typeof ApiV1ConfigRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/render': typeof ApiV1RenderRoute
  '/api/v1/admin/me': typeof ApiV1AdminMeRoute
  '/api/v1/comments/count': typeof ApiV1CommentsCountRoute
  '/api/v1/comments/recent': typeof ApiV1CommentsRecentRoute
  '/api/v1/threads/$': typeof ApiV1ThreadsSplatRoute
  '/api/v1/comments/': typeof ApiV1CommentsIndexRoute
  '/api/v1/admin/comments/$id': typeof ApiV1AdminCommentsIdRoute
  '/api/v1/admin/comments/batch': typeof ApiV1AdminCommentsBatchRoute
  '/api/v1/comments/$id/replies': typeof ApiV1CommentsIdRepliesRoute
  '/api/v1/admin/comments/': typeof ApiV1AdminCommentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/v1/config': typeof ApiV1ConfigRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/render': typeof ApiV1RenderRoute
  '/api/v1/admin/me': typeof ApiV1AdminMeRoute
  '/api/v1/comments/count': typeof ApiV1CommentsCountRoute
  '/api/v1/comments/recent': typeof ApiV1CommentsRecentRoute
  '/api/v1/threads/$': typeof ApiV1ThreadsSplatRoute
  '/api/v1/comments': typeof ApiV1CommentsIndexRoute
  '/api/v1/admin/comments/$id': typeof ApiV1AdminCommentsIdRoute
  '/api/v1/admin/comments/batch': typeof ApiV1AdminCommentsBatchRoute
  '/api/v1/comments/$id/replies': typeof ApiV1CommentsIdRepliesRoute
  '/api/v1/admin/comments': typeof ApiV1AdminCommentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/v1/config': typeof ApiV1ConfigRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/render': typeof ApiV1RenderRoute
  '/api/v1/admin/me': typeof ApiV1AdminMeRoute
  '/api/v1/comments/count': typeof ApiV1CommentsCountRoute
  '/api/v1/comments/recent': typeof ApiV1CommentsRecentRoute
  '/api/v1/threads/$': typeof ApiV1ThreadsSplatRoute
  '/api/v1/comments/': typeof ApiV1CommentsIndexRoute
  '/api/v1/admin/comments/$id': typeof ApiV1AdminCommentsIdRoute
  '/api/v1/admin/comments/batch': typeof ApiV1AdminCommentsBatchRoute
  '/api/v1/comments/$id/replies': typeof ApiV1CommentsIdRepliesRoute
  '/api/v1/admin/comments/': typeof ApiV1AdminCommentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/api/v1/config'
    | '/api/v1/health'
    | '/api/v1/render'
    | '/api/v1/admin/me'
    | '/api/v1/comments/count'
    | '/api/v1/comments/recent'
    | '/api/v1/threads/$'
    | '/api/v1/comments/'
    | '/api/v1/admin/comments/$id'
    | '/api/v1/admin/comments/batch'
    | '/api/v1/comments/$id/replies'
    | '/api/v1/admin/comments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/api/v1/config'
    | '/api/v1/health'
    | '/api/v1/render'
    | '/api/v1/admin/me'
    | '/api/v1/comments/count'
    | '/api/v1/comments/recent'
    | '/api/v1/threads/$'
    | '/api/v1/comments'
    | '/api/v1/admin/comments/$id'
    | '/api/v1/admin/comments/batch'
    | '/api/v1/comments/$id/replies'
    | '/api/v1/admin/comments'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/api/v1/config'
    | '/api/v1/health'
    | '/api/v1/render'
    | '/api/v1/admin/me'
    | '/api/v1/comments/count'
    | '/api/v1/comments/recent'
    | '/api/v1/threads/$'
    | '/api/v1/comments/'
    | '/api/v1/admin/comments/$id'
    | '/api/v1/admin/comments/batch'
    | '/api/v1/comments/$id/replies'
    | '/api/v1/admin/comments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ApiV1ConfigRoute: typeof ApiV1ConfigRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1RenderRoute: typeof ApiV1RenderRoute
  ApiV1AdminMeRoute: typeof ApiV1AdminMeRoute
  ApiV1CommentsCountRoute: typeof ApiV1CommentsCountRoute
  ApiV1CommentsRecentRoute: typeof ApiV1CommentsRecentRoute
  ApiV1ThreadsSplatRoute: typeof ApiV1ThreadsSplatRoute
  ApiV1CommentsIndexRoute: typeof ApiV1CommentsIndexRoute
  ApiV1AdminCommentsIdRoute: typeof ApiV1AdminCommentsIdRoute
  ApiV1AdminCommentsBatchRoute: typeof ApiV1AdminCommentsBatchRoute
  ApiV1CommentsIdRepliesRoute: typeof ApiV1CommentsIdRepliesRoute
  ApiV1AdminCommentsIndexRoute: typeof ApiV1AdminCommentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/config': {
      id: '/api/v1/config'
      path: '/api/v1/config'
      fullPath: '/api/v1/config'
      preLoaderRoute: typeof ApiV1ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/render': {
      id: '/api/v1/render'
      path: '/api/v1/render'
      fullPath: '/api/v1/render'
      preLoaderRoute: typeof ApiV1RenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/me': {
      id: '/api/v1/admin/me'
      path: '/api/v1/admin/me'
      fullPath: '/api/v1/admin/me'
      preLoaderRoute: typeof ApiV1AdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/': {
      id: '/api/v1/comments/'
      path: '/api/v1/comments'
      fullPath: '/api/v1/comments/'
      preLoaderRoute: typeof ApiV1CommentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/count': {
      id: '/api/v1/comments/count'
      path: '/api/v1/comments/count'
      fullPath: '/api/v1/comments/count'
      preLoaderRoute: typeof ApiV1CommentsCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/recent': {
      id: '/api/v1/comments/recent'
      path: '/api/v1/comments/recent'
      fullPath: '/api/v1/comments/recent'
      preLoaderRoute: typeof ApiV1CommentsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/threads/$': {
      id: '/api/v1/threads/$'
      path: '/api/v1/threads/$'
      fullPath: '/api/v1/threads/$'
      preLoaderRoute: typeof ApiV1ThreadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/comments/': {
      id: '/api/v1/admin/comments/'
      path: '/api/v1/admin/comments'
      fullPath: '/api/v1/admin/comments/'
      preLoaderRoute: typeof ApiV1AdminCommentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/comments/$id': {
      id: '/api/v1/admin/comments/$id'
      path: '/api/v1/admin/comments/$id'
      fullPath: '/api/v1/admin/comments/$id'
      preLoaderRoute: typeof ApiV1AdminCommentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/comments/batch': {
      id: '/api/v1/admin/comments/batch'
      path: '/api/v1/admin/comments/batch'
      fullPath: '/api/v1/admin/comments/batch'
      preLoaderRoute: typeof ApiV1AdminCommentsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/$id/replies': {
      id: '/api/v1/comments/$id/replies'
      path: '/api/v1/comments/$id/replies'
      fullPath: '/api/v1/comments/$id/replies'
      preLoaderRoute: typeof ApiV1CommentsIdRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ApiV1ConfigRoute: ApiV1ConfigRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1RenderRoute: ApiV1RenderRoute,
  ApiV1AdminMeRoute: ApiV1AdminMeRoute,
  ApiV1CommentsCountRoute: ApiV1CommentsCountRoute,
  ApiV1CommentsRecentRoute: ApiV1CommentsRecentRoute,
  ApiV1ThreadsSplatRoute: ApiV1ThreadsSplatRoute,
  ApiV1CommentsIndexRoute: ApiV1CommentsIndexRoute,
  ApiV1AdminCommentsIdRoute: ApiV1AdminCommentsIdRoute,
  ApiV1AdminCommentsBatchRoute: ApiV1AdminCommentsBatchRoute,
  ApiV1CommentsIdRepliesRoute: ApiV1CommentsIdRepliesRoute,
  ApiV1AdminCommentsIndexRoute: ApiV1AdminCommentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
